DROP DATABASE IF EXISTS ub7urmo990w2f5ke;
CREATE DATABASE ub7urmo990w2f5ke;

USE ub7urmo990w2f5ke;

CREATE TABLE  burgers (
    id INT AUTO_INCREMENT NOT NULL,
    burger_name VARCHAR(30) NOT NULL,
    devoured BOOLEAN,
    PRIMARY KEY(id)
);